// Shared demo feed until GET /api/wall/live-calls exists.
// Home and Live Calls read this so inbound/outbound stay in sync.

export const PLACEHOLDER_CALLS = [
  {
    id: "demo",
    patient: "Lucía Ruiz López",
    phase: "Talking",
    status: "live",
    duration: "00:32",
    language: "Español",
    direction: "inbound",
    phone: "+34 612 44 18 02",
    turns: [
      { id: 1, role: "user", text: "Hola, quería pedir cita para mi hija." },
      { id: 2, role: "assistant", text: "Claro. ¿Nombre completo y DNI de la paciente?" },
      { id: 3, role: "user", text: "Lucía Ruiz López, DNI 12345678Z." },
      { id: 4, role: "assistant", text: "Perfecto, te tengo localizada. ¿Qué día te viene bien?" },
    ],
    tools: [
      {
        id: "t1",
        tool: "find_patient",
        status: "ok",
        ms: 2380,
        args: { name: "Lucía Ruiz López", national_id: "12345678Z" },
        result: { status: "found", patient: { full_name: "Lucía Ruiz López", national_id: "12345678Z" } },
      },
    ],
  },
  {
    id: "call-2",
    patient: "Sin identificar",
    phase: "Listening",
    status: "live",
    duration: "00:08",
    language: "Català",
    direction: "inbound",
    phone: "+34 600 12 88 41",
    turns: [
      { id: 1, role: "assistant", text: "Bon dia, Clínica Arenal. Em pot dir el nom i el DNI?" },
      { id: 2, role: "user", text: "Un moment, el tinc al bolso…" },
    ],
  },
  {
    id: "call-3",
    patient: "Antonio Pérez Gil",
    phase: "Confirming slot",
    status: "live",
    duration: "01:14",
    language: "Español",
    direction: "inbound",
    phone: "+34 654 90 21 77",
    turns: [
      { id: 1, role: "user", text: "Quería cambiar la cita del martes con el Dr. Sáez." },
      { id: 2, role: "assistant", text: "Tengo el jueves a las 17:30. ¿Te encaja?" },
      { id: 3, role: "user", text: "Sí, esa." },
      { id: 4, role: "assistant", text: "Perfecto, te la dejo reservada. Te lo confirmo en un momento." },
    ],
    tools: [
      {
        id: "t1",
        tool: "find_patient",
        status: "ok",
        ms: 1210,
        args: { name: "Antonio Pérez Gil" },
        result: { status: "found", patient: { full_name: "Antonio Pérez Gil" } },
      },
      {
        id: "t2",
        tool: "list_appointments",
        status: "ok",
        ms: 540,
        args: { patient_id: "P00088" },
        result: { count: 1 },
      },
      {
        id: "t3",
        tool: "find_slots",
        status: "ok",
        ms: 980,
        args: { specialty_id: "medicina_general" },
        result: { slots: [{ start: "2026-09-24T17:30:00+02:00" }] },
      },
    ],
  },
  {
    id: "call-4",
    patient: "Ana Salas Ferrer",
    phase: "Escalated",
    status: "escalated",
    duration: "02:03",
    language: "Español",
    direction: "inbound",
    phone: "+34 622 08 55 13",
    turns: [
      { id: 1, role: "user", text: "Es una urgencia, le duele el pecho desde hace una hora." },
      { id: 2, role: "assistant", text: "Voy a pasarte ahora mismo con una persona de admisión." },
      { id: 3, role: "user", text: "Deprisa, por favor." },
    ],
    tools: [
      {
        id: "t1",
        tool: "find_patient",
        status: "ok",
        ms: 860,
        args: { name: "Ana Salas Ferrer" },
        result: { status: "found", patient: { full_name: "Ana Salas Ferrer" } },
      },
      { id: "t2", tool: "triage", status: "ok", ms: 310, args: { symptom: "dolor de pecho" }, result: { route: "emergency" } },
    ],
  },
  {
    id: "call-5",
    patient: "Miguel Costa Vidal",
    phase: "Reminder",
    status: "live",
    duration: "00:19",
    language: "Español",
    direction: "outbound",
    phone: "+34 671 33 09 64",
    turns: [
      { id: 1, role: "assistant", text: "Hola Miguel, te llamo de Clínica Arenal para recordarte la cita de mañana a las 10:00." },
      { id: 2, role: "user", text: "Sí, allí estaré. Gracias." },
    ],
  },
  {
    id: "call-6",
    patient: "Clara Puig Serra",
    phase: "Waitlist offer",
    status: "live",
    duration: "00:47",
    language: "Català",
    direction: "outbound",
    phone: "+34 649 21 70 05",
    turns: [
      { id: 1, role: "assistant", text: "Hola Clara, s'ha alliberat un forat demà a les 16:00 amb la Dra. Vidal. El vols?" },
      { id: 2, role: "user", text: "Sí, el vull. Gràcies." },
    ],
  },
];
