-- Every product table Vortex needs, hosted. Paste once in the SQL editor.
--
--   make supabase-ping
--   make supabase-push      -- call event log
--   make supabase-push-db   -- calls, appointments, cancellations, rebooking,
--                           -- voiceconfig, personalities
--
-- RLS is on and there are no public policies: only the service-role key
-- (the line and the board, never the browser) can read or write.

-- ---- call event log -------------------------------------------------------

create table if not exists public.call_events (
    id          bigint generated always as identity primary key,
    event_hash  text not null unique,
    ts          timestamptz not null,
    call_id     text not null,
    kind        text not null,
    event       jsonb not null
);

create index if not exists call_events_call_id_ts on public.call_events (call_id, ts);
create index if not exists call_events_ts on public.call_events (ts desc);

-- ---- product diary --------------------------------------------------------

create table if not exists public.calls (
    id              bigint generated by default as identity primary key,
    call_id         text not null unique,
    direction       text not null check (direction in ('inbound', 'outbound')),
    purpose         text not null check (
                        purpose in (
                            'booking', 'confirmation', 'cancellation',
                            'reschedule', 'info', 'other'
                        )
                    ),
    language        text,
    from_number     text,
    started_at      text not null,
    duration_ms     integer,
    outcome         text check (
                        outcome in (
                            'book', 'cancel', 'reschedule', 'register',
                            'no_action', 'escalate', 'confirmed', 'no_answer'
                        )
                    ),
    appointment_id  text
);

create index if not exists idx_calls_language on public.calls (language);
create index if not exists idx_calls_appointment_id on public.calls (appointment_id);
create index if not exists idx_calls_purpose on public.calls (purpose);

create table if not exists public.appointments (
    id                     text primary key,
    status                 text not null default 'scheduled' check (
                               status in (
                                   'scheduled', 'confirmed', 'cancelled',
                                   'completed', 'no_show'
                               )
                           ),
    patient_id             text not null,
    patient_name           text,
    patient_phone          text,
    patient_email          text,
    provider_id            text,
    provider_name          text,
    specialty_id           text,
    specialty_name         text,
    site_id                text,
    site_name              text,
    slot_start             text not null,
    slot_end               text not null,
    insurer                text,
    appointment_type_id    text,
    appointment_type_name  text,
    reason                 text,
    booking_call_id        bigint not null,
    confirmation_call_id   bigint,
    created_at             text not null,
    updated_at             text not null
);

create index if not exists idx_appointments_patient_id on public.appointments (patient_id);
create index if not exists idx_appointments_slot_start on public.appointments (slot_start);
create index if not exists idx_appointments_status on public.appointments (status);

create table if not exists public.wall_cancellations (
    id              bigint generated by default as identity primary key,
    provider_id     text not null,
    site_id         text not null,
    slot_start      text not null,
    appointment_id  text,
    patient_name    text,
    provider_name   text,
    cancelled_at    text not null
);

create index if not exists idx_wall_cancellations_slot
    on public.wall_cancellations (provider_id, site_id, slot_start);

-- ---- rebooking queue ------------------------------------------------------

create table if not exists public.rebooking_requests (
    request_id         text primary key,
    call_id            text not null,
    intent             text not null,
    status             text not null,
    patient_id         text not null,
    policy_id          text not null,
    date_from          text not null,
    date_to            text not null,
    time_from          text,
    time_to            text,
    specialty_id       text,
    provider_id        text,
    location_id        text,
    appointment_id     text,
    source_reason      text not null,
    created_at         text not null,
    updated_at         text not null,
    matched_slot_json  text,
    draft_action_json  text
);

-- ---- clinic console (settings, pathways, patterns) ------------------------

create table if not exists public.clinic_settings (
    id                                      integer primary key check (id = 1),
    minimum_booking_lead_hours              integer not null,
    patient_identification_fields_required  integer not null,
    call_time_cap_minutes                   integer not null,
    updated_at                              text not null
);

create table if not exists public.wall_documents (
    kind        text primary key,
    body        jsonb not null,
    updated_at  text not null
);

create table if not exists public.suggestion_rejections (
    patient_id   text not null,
    pattern_id   text not null,
    rejected_at  text not null,
    primary key (patient_id, pattern_id)
);

-- ---- agent voice + personas -----------------------------------------------

create table if not exists public.voiceconfig (
    id            integer primary key check (id = 1),
    voice         text not null,
    tone          integer not null,
    friendliness  integer not null,
    speech_rate   integer not null
);

create table if not exists public.personalities (
    slug            text primary key,
    name            text not null,
    role            text not null,
    description     text not null,
    tone            text not null,
    greetings_json  text not null,
    voices_json     text not null,
    avatar          text not null,
    sort_order      integer not null default 0,
    active          integer not null default 0,
    created_at      text not null,
    updated_at      text not null
);

-- ---- event-window helper (Home / Insights) --------------------------------

create or replace function public.call_events_for_window(
    p_max_calls integer default null,
    p_since timestamptz default null
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    with started as (
        select call_id, min(ts) as started_at
        from public.call_events
        group by call_id
    ),
    picked as (
        select s.call_id, s.started_at
        from started s
        where p_since is null or s.started_at >= p_since
        order by s.started_at desc
        -- Never unbounded. jsonb_agg over the whole table exceeds the
        -- statement timeout once the log passes a few hundred calls, and a
        -- timeout here reads as "Supabase is empty" to every caller.
        limit coalesce(p_max_calls, 1000)
    )
    select coalesce(jsonb_agg(e.event order by e.ts), '[]'::jsonb)
    from public.call_events e
    join picked p on p.call_id = e.call_id;
$$;

-- ---- lock it down ---------------------------------------------------------

alter table public.call_events enable row level security;
alter table public.calls enable row level security;
alter table public.appointments enable row level security;
alter table public.wall_cancellations enable row level security;
alter table public.rebooking_requests enable row level security;
alter table public.voiceconfig enable row level security;
alter table public.personalities enable row level security;
alter table public.clinic_settings enable row level security;
alter table public.wall_documents enable row level security;
alter table public.suggestion_rejections enable row level security;

revoke all on function public.call_events_for_window(integer, timestamptz)
    from public, anon, authenticated;
grant execute on function public.call_events_for_window(integer, timestamptz)
    to service_role;

grant all on table public.call_events to service_role;
grant all on table public.calls to service_role;
grant all on table public.appointments to service_role;
grant all on table public.wall_cancellations to service_role;
grant all on table public.rebooking_requests to service_role;
grant all on table public.voiceconfig to service_role;
grant all on table public.personalities to service_role;
grant all on table public.clinic_settings to service_role;
grant all on table public.wall_documents to service_role;
grant all on table public.suggestion_rejections to service_role;
grant usage, select on all sequences in schema public to service_role;
